# Generated by Django 5.1 on 2024-08-10 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mode_Souscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Moyen_Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Souscripteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('sexe', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('contact2', models.CharField(blank=True, max_length=50, null=True)),
                ('date_naissance', models.DateField()),
                ('lieu_naissance', models.CharField(max_length=50)),
                ('type_piece', models.CharField(max_length=50)),
                ('reference_piece', models.CharField(max_length=50)),
                ('date_delivrance', models.DateField()),
                ('situation_matrimoniale', models.CharField(max_length=50)),
                ('residence', models.CharField(max_length=50)),
                ('nationalite', models.CharField(max_length=50)),
                ('profession', models.CharField(max_length=50)),
                ('mot_de_passe', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('photo', models.FileField(blank=True, null=True, upload_to='photo_souscripteur')),
                ('date_saisie', models.DateTimeField(auto_now_add=True)),
                ('date_modif', models.DateTimeField(auto_now=True)),
                ('date_suppr', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Type_Personne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Souscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_souscription', models.CharField(max_length=50)),
                ('date_souscription', models.DateTimeField()),
                ('nbre_part_souscrit', models.IntegerField()),
                ('montant_total', models.FloatField()),
                ('montant_verse', models.FloatField()),
                ('montant_restant', models.FloatField()),
                ('lieu_souscription', models.CharField(max_length=50)),
                ('ref_paiement', models.CharField(max_length=50)),
                ('echeance', models.DateField()),
                ('pj1', models.FileField(blank=True, null=True, upload_to='pieces_jointes', verbose_name='pièce jointe 1')),
                ('pj2', models.FileField(blank=True, null=True, upload_to='pieces_jointes', verbose_name='pièce jointe 2')),
                ('pj3', models.FileField(blank=True, null=True, upload_to='pieces_jointes', verbose_name='pièce jointe 3')),
                ('observation', models.CharField(blank=True, max_length=50, null=True)),
                ('date_saisie', models.DateTimeField(auto_now_add=True)),
                ('date_modif', models.DateTimeField(auto_now=True)),
                ('date_suppr', models.DateTimeField(blank=True, null=True)),
                ('id_souscripteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='souscription.souscripteur')),
                ('mode_souscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='souscription.mode_souscription')),
                ('moyen_paiement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='souscription.moyen_paiement')),
                ('projet_a_souscrire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='souscription.projet')),
            ],
        ),
        migrations.AddField(
            model_name='souscripteur',
            name='type_personne',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='souscription.type_personne'),
        ),
    ]
