# Generated by Django 5.1 on 2024-08-10 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('souscription', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='souscripteur',
            name='type_personne',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Type_Personne',
        ),
    ]
