# Generated by Django 5.1 on 2024-08-10 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('souscription', '0002_alter_souscripteur_type_personne_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='souscription',
            name='mode_souscription',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='souscription',
            name='moyen_paiement',
            field=models.CharField(max_length=50),
        ),
    ]
