# Generated by Django 5.1 on 2024-08-10 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('souscription', '0003_alter_souscription_mode_souscription_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mode_Souscription',
        ),
    ]
