# Generated by Django 5.1 on 2024-08-11 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('souscription', '0005_remove_souscripteur_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Moyen_Paiement',
        ),
    ]
